set1 = ["geopotential_500",
        "mslp",
        "prec",
        "surface_temperature",
        "t850",
        "twv"
         ]


set2 = ["geopotential_250",
        "geopotential_500",
        "geopotential_850",
        "mslp",
        "potential_vorticity_500",
        "prec",
        "sic",
        "soil_moisture_layer_1",
        "surface_temperature",
        "t500",
        "twv",
        "u_500",
        "v_500",
        "u_900",
        "v_900",
         ]

set3 = ["geopotential_250",
        "geopotential_500",
        "geopotential_700",
        "geopotential_850",
        "mslp",
        "potential_vorticity_500",
        "potential_vorticity_300",
        "prec",
        "sic",
        "snow",
        "soil_moisture_layer_1",
        "surface_temperature",
        "t2m",
        "t500",
        "t850",
        "twv",
        "u_10m",
        "v_10m",
        "u_200",
        "v_200",
        "u_500",
        "v_500",
        "u_700",
        "v_700",
        "u_900",
        "v_900",
         ]

set4 = ["geopotential_250",
        "geopotential_500",
        "geopotential_700",
        "geopotential_850",
        "mslp",
        "potential_vorticity_500",
        "potential_vorticity_300",
        "prec",
        "sic",
        "soil_moisture_layer_1",
        "surface_temperature",
        "t2m",
        "t500",
        "t850",
        "twv",
        "u_10m",
        "v_10m",
        "u_200",
        "v_200",
        "u_500",
        "v_500",
        "u_700",
        "v_700",
        "u_900",
        "v_900",
         ]